
---
- name: Configure ARTEMIS Threat Hunting System
  hosts: elk
  become: true
  tasks:
  - name: Expand Mem Availability
    become: yes
    sysctl:
      name: vm.max_map_count
      value: '262144'
      reload: yes

  - name: Install Docker
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: Install Docker python module
    pip:
      name: docker
      state: present

  - name: Download and Launch ELK Container
    docker_container:
      name: elk
      image: sebp/elk:761
      state: started
      published_ports: 5601:5601, 9200:9200, 5044:5044